# Array manipulation routines

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: GTK3Agg


In [17]:
np.__version__

'1.17.4'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [18]:
print(np.ones([10, 10, 3]).reshape(2 ,150))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.reshape(x, 6, order='F')
x.reshape(-1, order='F')
np.ravel(x, order='F')
x.ravel(order='F')
print(x.flatten('F'))

[1 4 2 5 3 6]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [20]:
x = np.arange(1 ,7).reshape(2, 3)
#method 1
x[1][1]
#method 2
x.flat[4]
#method 3
x.flatten()[4]

5

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [21]:
x = np.zeros((3, 4, 5))
np.swapaxes(x, 1, 0).shape
x.transpose([1, 0, 2]).shape
#np.transpose(a, argsort(axes))

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [22]:
x = np.zeros((3, 4))
x.T
x.transpose()
#同理swapaxes也可以
x.T.shape

(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [23]:
np.expand_dims(np.zeros([3, 4]), axis=1).shape

(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [24]:
np.squeeze(np.zeros([3 ,4 ,1])).shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [25]:
x = np.arange(1, 7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
np.concatenate((x,y), axis=1)
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [26]:
np.concatenate((x,y))
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])
#method1
np.column_stack((x,y))
#method2
np.squeeze(np.dstack((x,y)))
#method3
np.stack((x,y) ,axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [28]:
x = x.reshape(3,1)
y = y.reshape(3,1)
np.concatenate((x,y),axis=1)
np.column_stack((x,y))
np.hstack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [29]:
x = np.arange(1,10)
#method 1
np.array_split(x,[4, 6])
np.split(x,[4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [44]:
x = np.arange(16).reshape(2,2,4)
np.dsplit(x, [3])
#also can use split
np.split(x,[3],axis=2)

[array([[[ 0,  1,  2],
         [ 4,  5,  6]],
 
        [[ 8,  9, 10],
         [12, 13, 14]]]),
 array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]])]

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [47]:
x = np.arange(16).reshape(4,4)
np.hsplit(x,2)
#use split
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [49]:
np.split(x,2)#default axis=0
#use vsplit
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [52]:
#method 1 use tile
x = np.arange(3)
np.tile(x,(2,2))
#method 2 use block
np.block([[x,x],[x,x]])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [55]:
print(np.repeat(x,2))

[0 0 1 1 2 2]


Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [56]:
x = np.array([0,0,0,1,2,3,0,2,1,0])
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [65]:
x = np.array([2,2,1,5,4,5,1,2,3])
for i in range(2):
    print(np.unique(x, return_counts=True)[i])

[1 2 3 4 5]
[2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [74]:
x = np.arange(1,5).reshape(2,2)
#1
np.flip(x,axis=1)
#2
np.fliplr(x)
#3
print(np.roll(x,1,axis=1))

[[2 1]
 [4 3]]


Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [72]:
#1
np.flip(x,axis=0)
#2
np.flipud(x)
#3
np.roll(x,1,axis=0)

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [77]:
x = np.arange(1,5).reshape(2,2)
#rot90(matrix, times, axes=(tup))
#if times>0 counter-clockwise
#elif clockwise
print(np.rot90(x))

[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [82]:
x = np.arange(1,9).reshape(2,4)
print(np.roll(x,1,axis=1))

[[4 1 2 3]
 [8 5 6 7]]
